version: "3.3"
services:
  web:
    image: bc_wildfire_web-1.0.0
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - backend_volume:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  frontend:
    image: bc_wildfire_ui-1.0.0
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - ./ui:/app

  db:
    image: postgres:13-alpine
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev

volumes:
  postgres-db-data:
  backend_volume:
