name: checks

on: 
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test
        run: docker-compose run --rm backend sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Build backend image
        run: |
          docker buildx build --file ./backend/Dockerfile --tag ${{ secrets.DOCKERHUB_USER }}/image-registry:backend_app-1.0.0 --push .

      - name: Build ui image
        run: |
          docker buildx build --file ./ui/Dockerfile --tag ${{ secrets.DOCKERHUB_USER }}/image-registry:frontend_app-1.0.0 --push .
     